---
name: Check BMT initialization daily

on:
  pull_request:
  schedule:
    - cron: '0 5 * * *'  # once per day at midnight ET
  workflow_dispatch:
  # Allows you to run this workflow manually from the Actions tab
    types: trigger-run-check-toolkit-initialization

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.9", "3.10", "3.11", "3.12" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: setup python environment
        with:
          python-version: ${{ matrix.python }}

      # this step we remove and rebuild the poetry.lock file to ensure that the tests that follow can be run
      # with the latest dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          rm -rf poetry.lock
          poetry install 

      - name: Run bmt tests
        run: |
          make test

      - name: Clone KGX and install dev branch of bmt
        run: |
          cd ../
          pwd
          git clone https://github.com/biolink/kgx.git
          cd kgx
          poetry install  # this will install a different version of hdmf from the current one
          docker run --detach --name kgx-neo4j-unit-test -p 8484:7474 -p 8888:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker run --detach --name kgx-neo4j-integration-test -p 7474:7474 -p 7687:7687 --env NEO4J_AUTH=neo4j/test neo4j:4.3.0
          docker ps -a
          poetry remove bmt
          ls -al ../
          poetry add /home/runner/work/biolink-model-toolkit/biolink-model-toolkit

      - name: Wait
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run kgx tests
        run: |  
          cd ../
          pwd
          cd kgx
          poetry run pytest tests/unit/test_source/*.py
          poetry run pytest tests/unit/test_sink/*.py
          poetry run pytest tests/unit/*.py
          poetry run pytest tests/integration/*.py